"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Get out of VI's compatible mode..
set nocompatible

"Sets how many lines of history VIM har to remember
set history=400

"plugin mamage
call pathogen#infect()

"Enable filetype plugin
filetype plugin on
filetype indent on

"Set to auto read when a file is changed from the outside
set autoread

"Have the mouse enabled all the time:
set mouse=a

"Set mapleader
let mapleader = ","
let g:mapleader = ","

"Fast remove highlight search
nmap <silent> <leader><cr> :noh<cr>

"fast saving
noremap <silent> <leader>ww :w<cr>

"unix-like slash
set ssl

"fast quiting
nmap <silent> <leader>qq :q<cr>
nmap <silent> <leader>fq :q!<cr>
nmap <silent> <leader>wq :wq<cr>

"cscope show in quickfix
set cscopequickfix=s-,c-,d-,i-,t-,e-

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  "autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else
  set autoindent		" always set autoindenting on
endif " has("autocmd")


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Colors and Fonts
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
set hlsearch
syntax on
if &t_Co > 2 || has("gui_running")
  set guioptions-=T
  set guioptions-=m
  set guioptions-=L
  set guioptions-=r
  "hi normal guibg=#294d4a
  colorscheme desert

  "Highlight current line

  "set cursorline
  "hi cursorline guibg=#666666
  "hi CursorColumn guibg=#666666
  "set guifont=Lucida_Console:h11:cANSI
else
  "colorscheme desert256
endif

autocmd BufEnter * :syntax sync fromstart


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Fileformats
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Favorite filetypes
if has('win32')
    set ffs=dos
else
    set ffs=unix
endif
"nmap <leader>fd :se ffs=dos<cr>
"nmap <leader>fu :se ffs=unix<cr>


"set encoding=utf-8
let &termencoding=&encoding 
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1
"set termencoding=utf-8
"set fencs=ucs-bom,SHIFT_JIS,EUC-JP,ISO-2022-JP,utf-8,gb18030,gbk,gb2312,big5,euc-jp,euc-kr,latin1,cp936
"set fencs=iso-2022-jp
"set fileencodings=utf-8,gbk,ucs-bom,cp936


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" VIM userinterface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Set 7 lines to the curors - when moving vertical..
set scrolloff=7

" Maximum window when GUI running
if has("gui_running")
  "set lines=120
  "set columns=220
endif

"When 'wildmenu' is on, command-line completion operates in an enhanced
set wildmenu

"display incomplete commands
set showcmd		

set showfulltag


"Always show current position
set ruler

" Don't use Ex mode, use Q for formatting
map Q gq

"The commandbar is 2 high
set cmdheight=2

"Show line number
set nu

"Do not redraw, when running macros.. lazyredraw
set lz

"Change buffer - without saving
"set hid

"Set backspace
set backspace=eol,start,indent

"Bbackspace and cursor keys wrap to
"set whichwrap+=<,>,h,l
set whichwrap+=<,>

"Ignore case when searching
set ignorecase

"Include search
set incsearch

"Set magic on
set magic

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

"No sound on errors.
set noerrorbells
set novisualbell
set t_vb=

"show matching bracets
"set showmatch

"How many tenths of a second to blink
"set mat=2

""""""""""""""""""""""""""""""
  " Statusline
""""""""""""""""""""""""""""""
"Always show the statusline
set laststatus=2

 function! CurDir()
     let curdir = substitute(getcwd(), glob('~'), "~", "g")
     return curdir
  endfunction


"Format the statusline
set statusline=\ %F%m%r%h\ %w\ \ CWD:\ %r%{CurDir()}%h\ \ \ Line:\ %l/%L:%c

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Moving around and tabs
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"window configuration
map <leader>wc ^Wc

"Tab configuration
map <leader>tn :tabnext
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
try
  set switchbuf=useopen
  set stal=1
catch
endtry


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Session options
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set sessionoptions-=curdir
set sessionoptions+=sesdir

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Files and backups
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Turn backup off
set nobackup
set nowb
set noswapfile

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Text options
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

"au FileType html,python,vim,javascript setl shiftwidth=2
"au FileType html,python,vim,javascript setl tabstop=2
"au FileType java,c setl shiftwidth=4
"au FileType java setl tabstop=4
"au FileType txt setl lbr
"au FileType txt setl tw=78

"set 'textwidth' to 78 characters.
"set lbr
"set tw=78

""""""""""""""""""""""""""""""
" Indent
""""""""""""""""""""""""""""""
"Auto indent
set ai

"Smart indet
set si

"C-style indeting
set cindent

"no Wrap lines
set nowrap


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Complete
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" options
set completeopt=menu
set complete-=u
set complete-=i

" Enable syntax
if has("autocmd") && exists("+omnifunc")
  autocmd Filetype *
        \if &omnifunc == "" |
        \  setlocal omnifunc=syntaxcomplete#Complete |
        \endif
endif


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin configuration
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

  """""""""""""""""""""""""
  " omnicpp setting
  """""""""""""""""""""""""""""

   let OmniCpp_SelectFirstItem = 2
   let OmniCpp_ShowPrototypeInAbbr = 1


   """"""""""""""""""""""""""""""
   " file explorer setting
   """"""""""""""""""""""""""""""
   "Split vertically
   let g:explVertical=1

   "Window size
   let g:explWinSize=35

   let g:explSplitLeft=1
   let g:explSplitBelow=1

   "Hide some files
   let g:explHideFiles='^\.,.*\.class$,.*\.swp$,.*\.pyc$,.*\.swo$,\.DS_Store$'

   "Hide the help thing..
   let g:explDetailedHelp=0


   """"""""""""""""""""""""""""""
   " bufexplorer setting
   """"""""""""""""""""""""""""""
   let g:bufExplorerDefaultHelp=1       " Do not show default help.
   let g:bufExplorerShowRelativePath=1  " Show relative paths.
   let g:bufExplorerSortBy='mru'        " Sort by most recently used.
   let g:bufExplorerSplitRight=0        " Split left.
   let g:bufExplorerSplitVertical=1     " Split vertically.
   let g:bufExplorerSplitVertSize = 30  " Split width
   let g:bufExplorerUseCurrentWindow=1  " Open in new window.
   let g:bufExplorerMaxHeight=13        " Max height

   """"""""""""""""""""""""""""""
   " taglist setting
   """"""""""""""""""""""""""""""
    if has('win32')
     let Tlist_Ctags_Cmd = '"'.$HOME.'\vimfiles\bins\ctags'.'"'
   else
     let Tlist_Ctags_Cmd = '/usr/bin/ctags'
   endif
   let Tlist_Show_One_File = 1
   let Tlist_Exit_OnlyWindow = 1
   "let Tlist_Use_Right_Window = 1
   nmap <silent> <leader>tl :Tlist<cr>

   """"""""""""""""""""""""""""""
   " netrw setting
   """"""""""""""""""""""""""""""
   let g:netrw_winsize = 30
   nmap <silent> <leader>fe :Sexplore!<cr>

   """"""""""""""""""""""""""""""
   " LaTeX Suite things
   """"""""""""""""""""""""""""""
   set grepprg=grep\ -nH\ $*
   let g:Tex_DefaultTargetFormat="pdf"
   let g:Tex_ViewRule_pdf='xpdf'
  "set shellslash

   "Bindings
   autocmd FileType tex map <silent><leader><space> :w!<cr> :silent! call Tex_RunLaTeX()<cr>

   "Auto complete some things ;)
   autocmd FileType tex inoremap $i \indent
   autocmd FileType tex inoremap $* \cdot
   autocmd FileType tex inoremap $i \item
   autocmd FileType tex inoremap $m \[<cr>\]<esc>O


   """"""""""""""""""""""""""""""""""""""""
   " FuzzyFinder settings
   """"""""""""""""""""""""""""""

   "map 
   "map <leader>fuf      :FufFile<cr>
   

   """"""""""""""""""""""""""""""
   " showmarks setting
   """"""""""""""""""""""""""""""
   " Enable ShowMarks
   let showmarks_enable = 1
   " Show which marks
   let showmarks_include = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
   " Ignore help, quickfix, non-modifiable buffers
   let showmarks_ignore_type = "hqm"
   " Hilight lower & upper marks
   "let showmarks_hlline_lower = 1
   "let showmarks_hlline_upper = 1

   """""""""""""""""""""""""""""""
   "NERD_TREE setings
   """"""""""""""""""""""""""""""
   let NERDTreeShowBookmarks=1
   let NERDTreeWinSize=25


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Filetype generic
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
   """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
   " Todo
   """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
   "au BufNewFile,BufRead *.todo so ~/vim_local/syntax/amido.vim

   """"""""""""""""""""""""""""""
   " HTML related
   """"""""""""""""""""""""""""""
   " HTML entities - used by xml edit plugin
   let xml_use_xhtml = 1
   "let xml_no_auto_nesting = 1

   "To HTML
   let html_use_css = 1
   let html_number_lines = 0
   let use_xhtml = 1

   """""""""""""""""""""""""""""""
   " Vim section
   """""""""""""""""""""""""""""""
   autocmd FileType vim set nofen
   autocmd FileType vim map <buffer> <leader><space> :w!<cr>:source %<cr>

   """"""""""""""""""""""""""""""
   " HTML
   """""""""""""""""""""""""""""""
   au FileType html set ft=xml
   au FileType html set syntax=html


   """"""""""""""""""""""""""""""
   " C/C++
   """""""""""""""""""""""""""""""
   autocmd FileType c,cpp  map <buffer> <leader><space> :make<cr>
   "autocmd FileType c,cpp  setl foldmethod=syntax | setl fen

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" MISC
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
   "Quickfix
   "nmap <leader>cn :cn<cr>
   "nmap <leader>cp :cp<cr>
   nmap <leader>cw :cw 10<cr>
   nmap <leader>co :copen<cr>
   "nmap <leader>cc :botright lw 10<cr>
   "map <c-u> <c-l><c-j>:q<cr>:botright cw 10<cr>

  
   "Paste toggle - when pasting something in, don't indent.
   set pastetoggle=<F3>
   "Super paste
   "inoremap <C-v> <esc>:set paste<cr>mui<C-R>+<esc>mv'uV'v=:set nopaste<cr>

   map <space> <C-f>
   map ; :

   nnoremap <F2>   :VimShell <cr>
   nnoremap <F3>   :exec "Grep ".expand('<cword>')<cr>
   nnoremap <C-F3> :GrepOptions<cr>
   nnoremap <F5>   :cnext <cr>
   nnoremap <C-F5> :cprevious<cr>
   "map <F6> :cd s:\SiriusE\program\<cr>
   "map <F5> :cd S:\SiriusL105\program<cr>
   map <F7> :cs add cscope.out<cr>
   map <F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR> <esc>:set tags=tags<cr>
   map <F11> :call Addcscope()<cr>
   map <C-F11> :call CscopeGen()<cr>
   map <leader>cd :cd <c-r>=expand("%:p:h")<cr>

   "map F8 to toggle the NERDTree
   nmap <F8> :NERDTree<cr>
   nmap <C-F8> :NERDTreeClose<cr>

   map <C-a> "+p
   map <C-c> "+y

   map <leader>fs :cs find s <c-r>=expand("<cword>")<cr>
   map <leader>fh :cs find s _<c-r>=expand("<cword>")<cr>
   map <leader>fg :cs find g <c-r>=expand("<cword>")<cr>
   map <leader>ff :sp<cr>:cs find f <c-r>=expand("<cfile>")<cr>
   map <leader>ft :call CsDoFindFile(expand("<cfile>"))<cr>
   "map <leader>jb :cd U:\yao.j\çÏã∆\è»ÉGÉl\src\program<cr>

  function! CsDoFindFile(b)
    let bef = strpart(a:b,0,strridx(a:b,"."))
    let aft = strpart(a:b,strridx(a:b,".")+1)
    let file = toupper(bef) . "." . tolower(aft)
    echo "file" . file
    cscope find f  <c-r>=file<cr>
  endfunction

"========================================================
" Highlight All Function
"========================================================
"highlight Functions
"syn match cFuntions display "[a-zA-Z_]\{-1,}\s\{-0,}(\{1}"ms=s,me=e-1
"hi def link cFuntions Title
"syn match   cFunction "\<[a-zA-Z_][a-zA-Z_0-9]*\>[^()]*)("me=e-2
"syn match   cFunction "\<[a-zA-Z_][a-zA-Z_0-9]*\>\s*("me=e-1
""hi cFunction cterm=bold ctermfg=4 gui=NONE guifg=#504301
"hi cFunction cterm=bold ctermfg=4 gui=NONE guifg=#504301

"set fencs=utf-8,

"
" grep function
"map <leader>grp :call Dogrep(expand("<cword>"))<cr>
"command!  -nargs=+ MyGrep execute 'silent vimgrep! <args> **/*.c **/*.h **/*.mar **/*.equ **/*.src **/*.inc' | copen         
"map <F3> :execute "grep -r  " . expand("<cword>") . "  **/*.c **/*.h **/*.mar **/*.equ **/*.src **/*.incÅ@**/*.s **/*.S" <bar>cw<cr>
"map  <F3> :execute "MyGrep " . expand("<cword>")<cr>
"map <F4> :execute "vimgrep /" . expand("<cword>") . "/gj " . "*.c *.h *.mar *.equ *.src *.inc" <bar>cw<cr>
"map <F4> :execute  "vimgrep /" . expand("<cword>") . "/gj " . "e:\**\*.c e:\**\*.h e:\**\*.mar e:\**\*.equ e:\**\*.src e:\**\*.inc" <bar>cw<cr>
"map <F4> :call Mfind(expand("<cword>"))<cr>
"
"function SavePosition()
  "let g:file_name=expand("%:t")
  "let g:line_number=line(".")
  "let g:reviewer_initials="KG" " Your initials
"endfunction

"function InsertComment()
  "execute "normal i". g:file_name . ":" . g:line_number . ": " . g:reviewer_initials . " - "
  "startinsert
"endfunction
"nmap ,sp :call SavePosition()<CR>
"nmap ,ic :call InsertComment()<CR>


function! Pyexe()
  let tempfile = tempname()
  echo %
  execute "!python % >" . tempfile
  execute "cfile" . tempfile
endfunction


" ================================
"   neocomplcache 
" =================================
    " set user custom snippt dir
    if has('win32')
        let g:neocomplcache_snippets_dir = $HOME.'/vimfiles/bundle/snippets_complete'
    else
        let g:neocomplcache_snippets_dir = $HOME.'/.vim/bundle/snippets_complete'
    endif
    " Disable AutoComplPop.
    let g:acp_enableAtStartup = 0
    " Use neocomplcache.
    let g:neocomplcache_enable_at_startup = 1
    " Use smartcase.
    let g:neocomplcache_enable_smart_case = 1
    " Use camel case completion.
    let g:neocomplcache_enable_camel_case_completion = 1
    " Use underbar completion.
    let g:neocomplcache_enable_underbar_completion = 1
    " Set minimum syntax keyword length.
    let g:neocomplcache_min_syntax_length = 3
    let g:neocomplcache_lock_buffer_name_pattern = '\*ku\*'

    " Define dictionary.
    let g:neocomplcache_dictionary_filetype_lists = {
        \ 'default' : '',
        \ 'vimshell' : $HOME.'/.vimshell_hist',
        \ 'scheme' : $HOME.'/.gosh_completions'
        \ }

    " Define keyword.
    if !exists('g:neocomplcache_keyword_patterns')
      let g:neocomplcache_keyword_patterns = {}
    endif
    let g:neocomplcache_keyword_patterns['default'] = '\h\w*'

    " Plugin key-mappings.
    imap <C-k>     <Plug>(neocomplcache_snippets_expand)
    smap <C-k>     <Plug>(neocomplcache_snippets_expand)
    inoremap <expr><C-g>     neocomplcache#undo_completion()
    inoremap <expr><C-l>     neocomplcache#complete_common_string()

    " SuperTab like snippets behavior.
    "imap <expr><TAB> neocomplcache#sources#snippets_complete#expandable() ? "\<Plug>(neocomplcache_snippets_expand)" : pumvisible() ? "\<C-n>" : "\<TAB>"

    " Recommended key-mappings.
    " <CR>: close popup and save indent.
    inoremap <expr><CR>  neocomplcache#smart_close_popup() . "\<CR>"
    " <TAB>: completion.
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    " <C-h>, <BS>: close popup and delete backword char.
    inoremap <expr><C-h> neocomplcache#smart_close_popup()."\<C-h>"
    inoremap <expr><BS> neocomplcache#smart_close_popup()."\<C-h>"
    inoremap <expr><C-y>  neocomplcache#close_popup()
    inoremap <expr><C-e>  neocomplcache#cancel_popup()

    " AutoComplPop like behavior.
    "let g:neocomplcache_enable_auto_select = 1

    " Shell like behavior(not recommended).
    "set completeopt+=longest
    "let g:neocomplcache_enable_auto_select = 1
    "let g:neocomplcache_disable_auto_complete = 1
    "inoremap <expr><TAB>  pumvisible() ? "\<Down>" : "\<TAB>"
    "inoremap <expr><CR>  neocomplcache#smart_close_popup() . "\<CR>"

    " Enable omni completion.
    autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
    autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
    autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
    autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
    autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

    " Enable heavy omni completion.
    if !exists('g:neocomplcache_omni_patterns')
      let g:neocomplcache_omni_patterns = {}
    endif
    let g:neocomplcache_omni_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'
    "autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete
    let g:neocomplcache_omni_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
    let g:neocomplcache_omni_patterns.c = '\%(\.\|->\)\h\w*'
    let g:neocomplcache_omni_patterns.cpp = '\h\w*\%(\.\|->\)\h\w*\|\h\w*::'


"" cscope
map <leader>fs : cs find s <c-r>=expand("<cword>")<CR>
map <leader>ff : cs find s <c-r>=expand("<cfile>")<CR>
map <leader>fr : call Addcscope()<cr>
map <leader>fg : call CscopeGen()<cr>

if has('win32')
    let g:cscope_bin= "~/.vim/bins/cscope.exe"
    let g:FindCmd = "~/.vim/bins/wfind.exe"
     let Tlist_Ctags_Cmd = "~/.vim/bins/ctags.exe"
else
    let g:cscope_bin = "cscope"
    let g:FindCmd = "find"
endif

function! Addcscope()
    cs kill 0
    echo "gen cscope.out"
    let cmd=g:cscope_bin." -bqk"
    echo cmd
    let ret = system(cmd)
    cs add cscope.out
endfunction

function! CscopeGen()
    if has("win32")
        let cmd = "dir /S /B *.c *.h *.s *.S *.cpp *.hpp *.cc *.hh *.hxx *.cxx *.hpp"
    else
        let cmd="find " . getcwd() . " -iname '*.h'  -or -iname '*.c'   -or -iname '*.cpp' -or -iname '*.hpp' -or -iname '*.cc' -or -iname '*.s'"
    endif

    let dst = getcwd()."/cscope.files"
    echo dst
    let ret = system(cmd)
    call writefile(split(ret), dst)
endfunction

function! KernelCscopeGen() 
    "let ret = system("~/.vim/bins/kernel-cscope.sh")
    "
endfunction

"let g:easy_grep_tempfile = tempname()
let g:easy_grep_tempfile = "hah.txt"

function! DoEasyGrep(keyword, path)
    if has("win32")
        "let cmd = "dir /S /B *.c *.h *.s *.S *.cpp *.hpp *.cc *.hh *.hxx *.cxx *.hpp"
        let cmd="grep -r  --include='*.h'  --include='*.c'  --include='*.cpp'  --include='*.hpp'  --include='*.cc' --include='*.s' --include='*.S' "
    else
        let cmd="grep -n -r  --include='*.h'  --include='*.c'  --include='*.cpp'  --include='*.hpp'  --include='*.cc' --include='*.s' --include='*.S' "
    endif
    
    let cmd = cmd  . " ".a:keyword."  ".a:path
    echomsg cmd 
    let ret = system(cmd)
    call writefile([ret], g:easy_grep_tempfile)
    "echomsg g:easy_grep_tempfile
    exec "cfile ".g:easy_grep_tempfile
    
endfunction
